-- AlterTable
ALTER TABLE "Offer" ADD COLUMN "highlights" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Offer" ADD COLUMN "features" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Offer" ADD COLUMN "included" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Offer" ADD COLUMN "notIncluded" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Offer" ADD COLUMN "terms" TEXT;
ALTER TABLE "Offer" ADD COLUMN "validUntil" TIMESTAMP(3);
